name: Update Eventos SCN Cache

on:
  schedule:
    # Ejecutar el primer día de cada mes a las 6:00 AM UTC
    - cron: '0 6 1 * *'
  workflow_dispatch: # Permitir ejecución manual

jobs:
  update-eventos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml
        
    - name: Run scraping script
      run: python .github/scripts/scrape_eventos.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/data/eventos-cache.json
        git diff --staged --quiet || git commit -m "Actualizar cache de eventos SCN - $(date +'%Y-%m')"
        git push